/**
 * Appointment booking flow (Phase 3).
 *
 * Transaction-safe creation of an appointment. The flow:
 *  1. Validate authenticated patient (caller ensures via authorize).
 *  2. Load chamber, verify active + doctor verified/available.
 *  3. Validate requested date (not past).
 *  4. Verify requested day is a visiting day.
 *  5. Verify requested time is inside working hours.
 *  6. Verify slot aligns to the chamber's slot grid + duration.
 *  7. Check slot availability (non-cancelled appt exists?).
 *  8. Compute serialNo inside the transaction.
 *  9. Create appointment atomically.
 * 10. appointmentNumber is DB-generated (sequence) → concurrency-safe.
 *
 * Double-booking protection is layered:
 *  - application check inside the transaction (step 7)
 *  - database partial unique index (chamberId, date, time) WHERE
 *    status != 'CANCELLED' → P2002 if a concurrent booking wins,
 *    mapped to HTTP 409 by the route handler.
 */
import { Prisma } from "@/lib/generated/prisma";
import { prisma } from "@/lib/prisma";
import { errors } from "@/lib/errors";
import { timeOfDay } from "@/lib/query";
import { buildSlotGrid, slotStartDate, weekdayAbbrev } from "./slots";
import type { Appointment } from "@/lib/generated/prisma";

export interface BookAppointmentInput {
  patientId: bigint;
  chamberId: bigint;
  date: string; // "YYYY-MM-DD"
  time: string; // "HH:mm"
  patientProblem?: string;
}

export interface BookingResult {
  appointment: Appointment;
}

/**
 * Validate the chamber, date, day, and slot boundaries. Returns the
 * normalized Date objects. Throws clean 400/404s on any violation.
 */
async function validateBookingContext(input: BookAppointmentInput): Promise<{
  chamber: NonNullable<Awaited<ReturnType<typeof loadChamberForBooking>>>;
  apptDate: Date;
  apptTime: Date;
  slotStart: Date;
}> {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(input.date)) {
    throw errors.badRequest("Appointment date must be in YYYY-MM-DD format");
  }
  if (!/^\d{2}:\d{2}$/.test(input.time)) {
    throw errors.badRequest("Appointment time must be in HH:mm format");
  }

  const apptDate = new Date(`${input.date}T00:00:00`);
  if (Number.isNaN(apptDate.getTime())) throw errors.badRequest("Invalid date");

  const chamber = await loadChamberForBooking(input.chamberId);
  if (!chamber) throw errors.notFound("Chamber not found");
  if (!chamber.isActive) throw errors.notFound("Chamber not found");
  if (chamber.deletedAt) throw errors.notFound("Chamber not found");
  if (!chamber.doctor.isVerified || !chamber.doctor.isAvailable) {
    throw errors.notFound("Chamber not found");
  }

  // Past date rejection (whole-day granularity).
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  if (apptDate.getTime() < today.getTime()) {
    throw errors.badRequest("Cannot book an appointment in the past");
  }

  // Visiting day check.
  const dayAbbrev = weekdayAbbrev(apptDate);
  const visiting = new Set(
    chamber.visitingDays.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean),
  );
  if (!visiting.has(dayAbbrev)) {
    throw errors.badRequest("The doctor does not visit this chamber on the selected day");
  }

  // Build the slot grid and confirm the requested time is an exact slot.
  const grid = buildSlotGrid(chamber, apptDate);
  const slotStart = slotStartDate(input.date, input.time);

  // Today's date: reject past time-of-day slots.
  if (slotStart.getTime() <= Date.now()) {
    throw errors.badRequest("Cannot book an appointment time that has already passed");
  }

  const matchingSlot = grid.find(
    (g) => g.start.getTime() === slotStart.getTime(),
  );
  if (!matchingSlot) {
    throw errors.badRequest("The requested time is not an available slot for this chamber");
  }

  const apptTime = timeOfDay(input.time);
  return { chamber, apptDate, apptTime, slotStart };
}

async function loadChamberForBooking(chamberId: bigint) {
  return prisma.chamber.findFirst({
    where: { id: chamberId },
    select: {
      id: true,
      doctorId: true,
      visitingDays: true,
      startTime: true,
      endTime: true,
      slotDurationMinutes: true,
      consultationFee: true,
      isActive: true,
      deletedAt: true,
      doctor: { select: { id: true, isVerified: true, isAvailable: true } },
    },
  });
}

/**
 * Create an appointment atomically inside a transaction.
 *
 * `serialNo` is computed as (count of non-cancelled appts for this
 * chamber+date) + 1, counted inside the transaction so it reflects
 * the committed state. `appointmentNumber` is DB-generated by the
 * sequence → safe under concurrency.
 *
 * Throws 409 (translated from P2002 by the route) if a concurrent
 * booking wins the slot. Bangla message per spec.
 */
export async function bookAppointment(input: BookAppointmentInput): Promise<BookingResult> {
  const { chamber, apptDate, apptTime } = await validateBookingContext(input);

  try {
    const appointment = await prisma.$transaction(async (tx) => {
      // Application-level availability check inside the transaction.
      const existing = await tx.appointment.findFirst({
        where: {
          chamberId: chamber.id,
          appointmentDate: apptDate,
          appointmentTime: apptTime,
          status: { not: "CANCELLED" },
        },
        select: { id: true },
      });
      if (existing) {
        throw errors.conflict("এই সময়ের স্লটটি ইতোমধ্যে বুক করা হয়েছে।");
      }

      // serialNo for this chamber+date (sequence within the day).
      const count = await tx.appointment.count({
        where: {
          chamberId: chamber.id,
          appointmentDate: apptDate,
          status: { not: "CANCELLED" },
        },
      });

      return tx.appointment.create({
        data: {
          patientId: input.patientId,
          doctorId: chamber.doctorId,
          chamberId: chamber.id,
          appointmentDate: apptDate,
          appointmentTime: apptTime,
          serialNo: count + 1,
          fee: chamber.consultationFee,
          patientProblem: input.patientProblem ?? null,
          status: "PENDING",
        },
      });
    });

    return { appointment };
  } catch (err) {
    // Database-level double-booking guard: the partial unique index
    // (chamberId, appointmentDate, appointmentTime) WHERE status !=
    // 'CANCELLED' throws P2002 if a concurrent booking inserted first.
    if (isPrismaUniqueViolation(err)) {
      throw errors.conflict("এই সময়ের স্লটটি ইতোমধ্যে বুক করা হয়েছে।");
    }
    // HttpErrors (e.g. our 409 above) pass through unchanged.
    throw err;
  }
}

function isPrismaUniqueViolation(err: unknown): boolean {
  return (
    typeof err === "object" &&
    err !== null &&
    "code" in err &&
    (err as { code: string }).code === "P2002"
  );
}

/** Type guard helper for Prisma Decimal serialization. */
export function decimalToString(d: Prisma.Decimal | string | number): string {
  if (typeof d === "string") return d;
  if (typeof d === "number") return String(d);
  return d.toString();
}
